print("Hello!")
name=input("What is your name? ")
print("Hello, "+ name + " a pleasure to meet you!")
num_1=int(input("What is your age? "))
print("Thank you.")
num_2=int(input("Can you enter a number? "))
num_3=int(input("Can you now tell me what day of the month is it? "))
print("Thank you, I will now multiply these numbers together and display the result!")
print(num_1 * num_2 * num_3)